### ISSUE TITLE
feature request: make variables available before bootstrap phase

### ISSUE THREAD

**Issue by feedm3** [luanbitar/gatsby-env-variables#1]
First of all: Thank you for the plugin, it does it's just really well 👏 ! It makes managing multiple environment files very easy. But unfortunatelly, not everywhere in the gatsby project.

It would be really helpful to also have the same environment variables available before the `bootstrap` phase. For example in the `gatsby-node.js` file for some API configs. As this plugin uses `onCreateWebpackConfig` it runs too late and it's therefore not possible to use `process.env.EXAMPLE_VARIABLE` there. To fix this issue, I'm currently running `require('dotenv').config(...)` manually in the `gatsby-node.js` file. This is duplicate code, as I have to run more or less the same code as this plugin runs.

Is it somehow possible to run the `require('dotenv').config(...)` command as one of the first command in gatsby, and also run it again in `onCreateWebpackConfig`, all within this plugin?

**Comment by luanbitar** [comment]
Hi @feedm3, really appreciate your feedback and thank you for liking the plugin, in version `2.0.0` it's possible to load env's with imports, in the first time of the build runs, all compiled vars are saved on `.json` file, the second time you run build, all variables will be available in any step, see how do you use:

```js
import { API_ROOT, CARDS } from "gatsby-env-variables"

function Example() {
  const cardsURL = API_ROOT + CARDS // stg.example.com/cards
  fetch(cardsURL)
}
```

Again, thanks :v:
