### ISSUE TITLE
how to build the app for staging or production

### ISSUE THREAD

**Issue by aikodeio** [luanbitar/gatsby-env-variables#2]
I have my environment files with their respective variables.

How should I configure the package.json file so that when I compile for staging, it considers me the staging environment and if I compile for production it considers me the production environment?

I'm confused.
Thank you

**Comment by aikodeio** [comment]
I don't understand this step:

`BUILD_ENV=staging yarn start`

my package.json file has the following script:
```
...
"scripts": {
    "develop": "gatsby develop",
    "start": "npm run develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
}
...
```

**Comment by aikodeio** [comment]
@luanbitar help plis :( thanks

**Comment by luanbitar** [comment]
Hi @aikodeio, you will tell what environment you want to build, you can do this when you will run the commands, like `BUILD_ENV=staging yarn build` in your terminal if you want to build using staging config, or you can create a npm script to do this, 
```
"scripts": {
    "develop": "gatsby develop",
    "start": "npm run develop",
    "build": "gatsby build",
	"build:staging": "BUILD_ENV=staging yarn build",
    "serve": "gatsby serve"
}
```

Did you understand?

**Comment by aikodeio** [comment]
@luanbitar Thanks for answering me.

I am executing the following command in the console

`BUILD_ENV=staging yarn build`

but I get the following error:

"BUILD_ENV" is not recognized as an internal or external command,
program or executable batch file.

Do I need to add something else?

**Comment by aikodeio** [comment]
```
{
    "name": "test-env",
    "private": true,
    "version": "1.0.0",
    "dependencies": {
        "gatsby": "^2.20.7",
        "gatsby-env-variables": "^2.0.0",
        "gatsby-image": "^2.3.1",
        "gatsby-plugin-manifest": "^2.3.3",
        "gatsby-plugin-offline": "^3.1.2",
        "gatsby-plugin-react-helmet": "^3.2.1",
        "gatsby-plugin-remove-trailing-slashes": "^2.2.1",
        "gatsby-plugin-sharp": "^2.5.3",
        "gatsby-source-filesystem": "^2.2.2",
        "gatsby-transformer-sharp": "^2.4.2",
        "prop-types": "^15.7.2",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "react-helmet": "^5.2.1",
    },
    "devDependencies": {
        "prettier": "^1.19.1"
    },
    "scripts": {
        "develop": "gatsby develop",
        "build": "gatsby build",
        "build:staging": "BUILD_ENV=staging yarn build",
        "build:production": "BUILD_ENV=production yarn build",
        "serve": "gatsby serve"
    }
}
```

**Comment by aikodeio** [comment]
@luanbitar excuse the insistence bro. But I cannot execute this

**Comment by lucasljsb** [comment]
@aikodeio 
I had the same problem. Corrected combining with **[cross-env](https://www.npmjs.com/package/cross-env)**, like this:

`{
  "scripts": {
    "build": "cross-env BUILD_ENV=production gatsby build"
  }
}`

I hope this helps you.

**Comment by aikodeio** [comment]
@lucasljsb Thank you! it worked perfectly
