### ISSUE TITLE
require(cachedVariables.json) fails if it doesn't exist

### ISSUE THREAD

**Issue by NICHTJ3** [luanbitar/gatsby-env-variables#6]
**Describe the bug**
Pretty much what the title says. When using this plugin with storybook importing values from this plugin fail

**To Reproduce**
Try use storybook in your gatsby project

**Expected behavior**
cachedVariables.json should only be read if it exists so that the plugin fails gracefully

**Comment by victorvoid** [comment]
up

**Comment by hedgepaybsc** [comment]
Same issue here

**Comment by niko1aew** [comment]
up

**Comment by luanbitar** [comment]
fixed here https://github.com/luanbitar/gatsby-env-variables/pull/7
